interface Customer {
  customer_id: string;
  name: string;
  email: string;
}

interface Order {
  order_id: string;
  customer_id: string;
  item: string;
  status: "pending" | "shipped" | "delivered";
  amount: number;
}

export const customers: Customer[] = [
  {
    customer_id: "CUST-001",
    name: "田中 太郎",
    email: "taro.tanaka@example.com",
  },
  {
    customer_id: "CUST-002",
    name: "鈴木 花子",
    email: "hanako.suzuki@example.com",
  },
  {
    customer_id: "CUST-003",
    name: "佐藤 一郎",
    email: "ichiro.sato@example.com",
  },
  {
    customer_id: "CUST-004",
    name: "高橋 美咲",
    email: "misaki.takahashi@example.com",
  },
  {
    customer_id: "CUST-005",
    name: "伊藤 健太",
    email: "kenta.ito@example.com",
  },
  {
    customer_id: "CUST-006",
    name: "渡辺 さくら",
    email: "sakura.watanabe@example.com",
  },
  {
    customer_id: "CUST-007",
    name: "山本 誠",
    email: "makoto.yamamoto@example.com",
  },
  {
    customer_id: "CUST-008",
    name: "中村 優子",
    email: "yuko.nakamura@example.com",
  },
  {
    customer_id: "CUST-009",
    name: "小林 拓也",
    email: "takuya.kobayashi@example.com",
  },
  {
    customer_id: "CUST-010",
    name: "加藤 里奈",
    email: "rina.kato@example.com",
  },
  {
    customer_id: "CUST-011",
    name: "吉田 浩二",
    email: "koji.yoshida@example.com",
  },
  {
    customer_id: "CUST-012",
    name: "山田 彩香",
    email: "ayaka.yamada@example.com",
  },
  {
    customer_id: "CUST-013",
    name: "松本 大輔",
    email: "daisuke.matsumoto@example.com",
  },
  {
    customer_id: "CUST-014",
    name: "井上 奈々",
    email: "nana.inoue@example.com",
  },
  {
    customer_id: "CUST-015",
    name: "木村 翔太",
    email: "shota.kimura@example.com",
  },
  {
    customer_id: "CUST-016",
    name: "林 真由美",
    email: "mayumi.hayashi@example.com",
  },
  {
    customer_id: "CUST-017",
    name: "清水 龍",
    email: "ryu.shimizu@example.com",
  },
  {
    customer_id: "CUST-018",
    name: "山口 麻衣",
    email: "mai.yamaguchi@example.com",
  },
  {
    customer_id: "CUST-019",
    name: "斎藤 俊介",
    email: "shunsuke.saito@example.com",
  },
  {
    customer_id: "CUST-020",
    name: "松田 朱音",
    email: "akane.matsuda@example.com",
  },
  {
    customer_id: "CUST-021",
    name: "岡田 航",
    email: "wataru.okada@example.com",
  },
  {
    customer_id: "CUST-022",
    name: "橋本 千尋",
    email: "chihiro.hashimoto@example.com",
  },
  {
    customer_id: "CUST-023",
    name: "石川 隆",
    email: "takashi.ishikawa@example.com",
  },
  {
    customer_id: "CUST-024",
    name: "前田 沙織",
    email: "saori.maeda@example.com",
  },
  { customer_id: "CUST-025", name: "藤田 悠", email: "yu.fujita@example.com" },
  {
    customer_id: "CUST-026",
    name: "後藤 みのり",
    email: "minori.goto@example.com",
  },
  { customer_id: "CUST-027", name: "近藤 亮", email: "ryo.kondo@example.com" },
  {
    customer_id: "CUST-028",
    name: "村上 綾乃",
    email: "ayano.murakami@example.com",
  },
  {
    customer_id: "CUST-029",
    name: "長谷川 慎",
    email: "shin.hasegawa@example.com",
  },
  {
    customer_id: "CUST-030",
    name: "坂本 遥",
    email: "haruka.sakamoto@example.com",
  },
  {
    customer_id: "CUST-031",
    name: "石田 雄大",
    email: "yudai.ishida@example.com",
  },
  {
    customer_id: "CUST-032",
    name: "内田 楓",
    email: "kaede.uchida@example.com",
  },
  {
    customer_id: "CUST-033",
    name: "宮崎 光",
    email: "hikaru.miyazaki@example.com",
  },
  {
    customer_id: "CUST-034",
    name: "福田 詩織",
    email: "shiori.fukuda@example.com",
  },
  {
    customer_id: "CUST-035",
    name: "谷口 大地",
    email: "daichi.taniguchi@example.com",
  },
  {
    customer_id: "CUST-036",
    name: "西村 春香",
    email: "haruka.nishimura@example.com",
  },
  {
    customer_id: "CUST-037",
    name: "藤井 聡",
    email: "satoshi.fujii@example.com",
  },
  {
    customer_id: "CUST-038",
    name: "岩田 梨花",
    email: "rika.iwata@example.com",
  },
  {
    customer_id: "CUST-039",
    name: "中島 颯",
    email: "hayate.nakashima@example.com",
  },
  { customer_id: "CUST-040", name: "平野 萌", email: "moe.hirano@example.com" },
  {
    customer_id: "CUST-041",
    name: "浜田 純一",
    email: "junichi.hamada@example.com",
  },
  {
    customer_id: "CUST-042",
    name: "野口 舞",
    email: "mai.noguchi@example.com",
  },
  {
    customer_id: "CUST-043",
    name: "上野 正樹",
    email: "masaki.ueno@example.com",
  },
  {
    customer_id: "CUST-044",
    name: "菊地 美穂",
    email: "miho.kikuchi@example.com",
  },
  {
    customer_id: "CUST-045",
    name: "原田 拓",
    email: "taku.harada@example.com",
  },
  {
    customer_id: "CUST-046",
    name: "川口 知恵",
    email: "chie.kawaguchi@example.com",
  },
  { customer_id: "CUST-047", name: "三浦 諒", email: "ryo.miura@example.com" },
  {
    customer_id: "CUST-048",
    name: "福島 葵",
    email: "aoi.fukushima@example.com",
  },
  { customer_id: "CUST-049", name: "新井 俊", email: "shun.arai@example.com" },
  {
    customer_id: "CUST-050",
    name: "池田 真央",
    email: "mao.ikeda@example.com",
  },
  {
    customer_id: "CUST-051",
    name: "杉山 和也",
    email: "kazuya.sugiyama@example.com",
  },
  {
    customer_id: "CUST-052",
    name: "金子 華",
    email: "hana.kaneko@example.com",
  },
  {
    customer_id: "CUST-053",
    name: "藤原 悟",
    email: "satoru.fujiwara@example.com",
  },
  {
    customer_id: "CUST-054",
    name: "工藤 莉子",
    email: "riko.kudo@example.com",
  },
  {
    customer_id: "CUST-055",
    name: "丸山 直人",
    email: "naoto.maruyama@example.com",
  },
  {
    customer_id: "CUST-056",
    name: "今井 ひかる",
    email: "hikaru.imai@example.com",
  },
  {
    customer_id: "CUST-057",
    name: "阿部 裕介",
    email: "yusuke.abe@example.com",
  },
  {
    customer_id: "CUST-058",
    name: "小川 七海",
    email: "nanami.ogawa@example.com",
  },
  {
    customer_id: "CUST-059",
    name: "大野 修平",
    email: "shuhei.ono@example.com",
  },
  {
    customer_id: "CUST-060",
    name: "竹内 あかり",
    email: "akari.takeuchi@example.com",
  },
  {
    customer_id: "CUST-061",
    name: "増田 稔",
    email: "minoru.masuda@example.com",
  },
  {
    customer_id: "CUST-062",
    name: "河野 のぞみ",
    email: "nozomi.kono@example.com",
  },
  {
    customer_id: "CUST-063",
    name: "辻 篤史",
    email: "atsushi.tsuji@example.com",
  },
  {
    customer_id: "CUST-064",
    name: "宮本 碧",
    email: "midori.miyamoto@example.com",
  },
  {
    customer_id: "CUST-065",
    name: "永田 宏",
    email: "hiroshi.nagata@example.com",
  },
  {
    customer_id: "CUST-066",
    name: "黒木 柚希",
    email: "yuzuki.kuroki@example.com",
  },
  {
    customer_id: "CUST-067",
    name: "村田 海斗",
    email: "kaito.murata@example.com",
  },
  {
    customer_id: "CUST-068",
    name: "大石 紗耶",
    email: "saya.oishi@example.com",
  },
  {
    customer_id: "CUST-069",
    name: "野村 泰輔",
    email: "taisuke.nomura@example.com",
  },
  {
    customer_id: "CUST-070",
    name: "坂井 椎奈",
    email: "shiina.sakai@example.com",
  },
  {
    customer_id: "CUST-071",
    name: "田村 芳樹",
    email: "yoshiki.tamura@example.com",
  },
  {
    customer_id: "CUST-072",
    name: "横山 このみ",
    email: "konomi.yokoyama@example.com",
  },
  {
    customer_id: "CUST-073",
    name: "和田 慶一",
    email: "keiichi.wada@example.com",
  },
  { customer_id: "CUST-074", name: "千葉 鈴", email: "suzu.chiba@example.com" },
  {
    customer_id: "CUST-075",
    name: "松井 将太",
    email: "shota.matsui@example.com",
  },
  { customer_id: "CUST-076", name: "奥田 杏", email: "an.okuda@example.com" },
  {
    customer_id: "CUST-077",
    name: "菅原 義弘",
    email: "yoshihiro.sugawara@example.com",
  },
  {
    customer_id: "CUST-078",
    name: "堀 ことね",
    email: "kotone.hori@example.com",
  },
  {
    customer_id: "CUST-079",
    name: "塚本 剛",
    email: "go.tsukamoto@example.com",
  },
  {
    customer_id: "CUST-080",
    name: "秋山 芽依",
    email: "mei.akiyama@example.com",
  },
  {
    customer_id: "CUST-081",
    name: "富田 啓介",
    email: "keisuke.tomita@example.com",
  },
  {
    customer_id: "CUST-082",
    name: "桑原 凛",
    email: "rin.kuwahara@example.com",
  },
  {
    customer_id: "CUST-083",
    name: "上田 博之",
    email: "hiroyuki.ueda@example.com",
  },
  {
    customer_id: "CUST-084",
    name: "安藤 夕夏",
    email: "yuka.ando@example.com",
  },
  {
    customer_id: "CUST-085",
    name: "荒木 達也",
    email: "tatsuya.araki@example.com",
  },
  {
    customer_id: "CUST-086",
    name: "武田 美緒",
    email: "mio.takeda@example.com",
  },
  {
    customer_id: "CUST-087",
    name: "島田 純平",
    email: "junpei.shimada@example.com",
  },
  {
    customer_id: "CUST-088",
    name: "森田 いずみ",
    email: "izumi.morita@example.com",
  },
  {
    customer_id: "CUST-089",
    name: "久保田 亘",
    email: "wataru.kubota@example.com",
  },
  {
    customer_id: "CUST-090",
    name: "石橋 結菜",
    email: "yuna.ishibashi@example.com",
  },
  {
    customer_id: "CUST-091",
    name: "高木 昌弘",
    email: "masahiro.takagi@example.com",
  },
  {
    customer_id: "CUST-092",
    name: "澤田 夏希",
    email: "natsuki.sawada@example.com",
  },
  {
    customer_id: "CUST-093",
    name: "沢田 智也",
    email: "tomoya.sawada@example.com",
  },
  {
    customer_id: "CUST-094",
    name: "牧野 琴音",
    email: "kotone.makino@example.com",
  },
  {
    customer_id: "CUST-095",
    name: "桜井 祐樹",
    email: "yuki.sakurai@example.com",
  },
  {
    customer_id: "CUST-096",
    name: "市川 栞",
    email: "shiori.ichikawa@example.com",
  },
  {
    customer_id: "CUST-097",
    name: "本田 誠一",
    email: "seiichi.honda@example.com",
  },
  {
    customer_id: "CUST-098",
    name: "田川 ほのか",
    email: "honoka.tagawa@example.com",
  },
  {
    customer_id: "CUST-099",
    name: "星野 貴文",
    email: "takafumi.hoshino@example.com",
  },
  { customer_id: "CUST-100", name: "倉田 彩", email: "aya.kurata@example.com" },
];

export const orders: Order[] = [
  {
    order_id: "ORD-001",
    customer_id: "CUST-003",
    item: "ワイヤレスイヤホン",
    status: "delivered",
    amount: 12800,
  },
  {
    order_id: "ORD-002",
    customer_id: "CUST-017",
    item: "スマートウォッチ",
    status: "shipped",
    amount: 34500,
  },
  {
    order_id: "ORD-003",
    customer_id: "CUST-041",
    item: "ノートパソコン用スタンド",
    status: "pending",
    amount: 5980,
  },
  {
    order_id: "ORD-004",
    customer_id: "CUST-008",
    item: "メカニカルキーボード",
    status: "delivered",
    amount: 18900,
  },
  {
    order_id: "ORD-005",
    customer_id: "CUST-055",
    item: "USBハブ",
    status: "shipped",
    amount: 3200,
  },
  {
    order_id: "ORD-006",
    customer_id: "CUST-022",
    item: "Webカメラ",
    status: "delivered",
    amount: 8750,
  },
  {
    order_id: "ORD-007",
    customer_id: "CUST-063",
    item: "外付けSSD 1TB",
    status: "pending",
    amount: 14500,
  },
  {
    order_id: "ORD-008",
    customer_id: "CUST-031",
    item: "モニター 27インチ",
    status: "shipped",
    amount: 52000,
  },
  {
    order_id: "ORD-009",
    customer_id: "CUST-076",
    item: "マウスパッド",
    status: "delivered",
    amount: 1500,
  },
  {
    order_id: "ORD-010",
    customer_id: "CUST-049",
    item: "ゲーミングマウス",
    status: "delivered",
    amount: 9800,
  },
  {
    order_id: "ORD-011",
    customer_id: "CUST-014",
    item: "ヘッドセット",
    status: "pending",
    amount: 7600,
  },
  {
    order_id: "ORD-012",
    customer_id: "CUST-088",
    item: "Bluetooth スピーカー",
    status: "shipped",
    amount: 6200,
  },
  {
    order_id: "ORD-013",
    customer_id: "CUST-035",
    item: "ケーブルオーガナイザー",
    status: "delivered",
    amount: 980,
  },
  {
    order_id: "ORD-014",
    customer_id: "CUST-002",
    item: "ノートPC バッグ",
    status: "delivered",
    amount: 4500,
  },
  {
    order_id: "ORD-015",
    customer_id: "CUST-071",
    item: "スマートフォンスタンド",
    status: "pending",
    amount: 1200,
  },
  {
    order_id: "ORD-016",
    customer_id: "CUST-046",
    item: "タブレット 10インチ",
    status: "shipped",
    amount: 42800,
  },
  {
    order_id: "ORD-017",
    customer_id: "CUST-019",
    item: "ゲーミングチェア",
    status: "delivered",
    amount: 38000,
  },
  {
    order_id: "ORD-018",
    customer_id: "CUST-082",
    item: "デスクライト",
    status: "delivered",
    amount: 3800,
  },
  {
    order_id: "ORD-019",
    customer_id: "CUST-007",
    item: "ワイヤレス充電器",
    status: "shipped",
    amount: 4200,
  },
  {
    order_id: "ORD-020",
    customer_id: "CUST-060",
    item: "ラップトップクーラー",
    status: "pending",
    amount: 3500,
  },
  {
    order_id: "ORD-021",
    customer_id: "CUST-033",
    item: "スマートプラグ",
    status: "delivered",
    amount: 2800,
  },
  {
    order_id: "ORD-022",
    customer_id: "CUST-095",
    item: "HDMIケーブル 2m",
    status: "shipped",
    amount: 1200,
  },
  {
    order_id: "ORD-023",
    customer_id: "CUST-011",
    item: "ポータブルバッテリー",
    status: "delivered",
    amount: 6500,
  },
  {
    order_id: "ORD-024",
    customer_id: "CUST-068",
    item: "ノイズキャンセリングヘッドホン",
    status: "pending",
    amount: 28000,
  },
  {
    order_id: "ORD-025",
    customer_id: "CUST-044",
    item: "デジタルフォトフレーム",
    status: "shipped",
    amount: 9800,
  },
  {
    order_id: "ORD-026",
    customer_id: "CUST-026",
    item: "スマートホームハブ",
    status: "delivered",
    amount: 12500,
  },
  {
    order_id: "ORD-027",
    customer_id: "CUST-057",
    item: "電動スタンディングデスク",
    status: "pending",
    amount: 85000,
  },
  {
    order_id: "ORD-028",
    customer_id: "CUST-073",
    item: "ルーター Wi-Fi 6",
    status: "shipped",
    amount: 18000,
  },
  {
    order_id: "ORD-029",
    customer_id: "CUST-039",
    item: "NAS 2ベイ",
    status: "delivered",
    amount: 24000,
  },
  {
    order_id: "ORD-030",
    customer_id: "CUST-016",
    item: "プリンター複合機",
    status: "shipped",
    amount: 22000,
  },
  {
    order_id: "ORD-031",
    customer_id: "CUST-084",
    item: "スキャナー A4",
    status: "pending",
    amount: 16000,
  },
  {
    order_id: "ORD-032",
    customer_id: "CUST-051",
    item: "グラフィックタブレット",
    status: "delivered",
    amount: 31000,
  },
  {
    order_id: "ORD-033",
    customer_id: "CUST-028",
    item: "ポータブルプロジェクター",
    status: "shipped",
    amount: 45000,
  },
  {
    order_id: "ORD-034",
    customer_id: "CUST-066",
    item: "スマートリモコン",
    status: "delivered",
    amount: 3800,
  },
  {
    order_id: "ORD-035",
    customer_id: "CUST-090",
    item: "Type-C ドッキングステーション",
    status: "pending",
    amount: 11200,
  },
  {
    order_id: "ORD-036",
    customer_id: "CUST-005",
    item: "ゲーミングヘッドセット",
    status: "shipped",
    amount: 15800,
  },
  {
    order_id: "ORD-037",
    customer_id: "CUST-038",
    item: "アクションカメラ",
    status: "delivered",
    amount: 38000,
  },
  {
    order_id: "ORD-038",
    customer_id: "CUST-079",
    item: "ミラーレスカメラ",
    status: "pending",
    amount: 125000,
  },
  {
    order_id: "ORD-039",
    customer_id: "CUST-023",
    item: "交換レンズ 50mm",
    status: "shipped",
    amount: 68000,
  },
  {
    order_id: "ORD-040",
    customer_id: "CUST-100",
    item: "三脚",
    status: "delivered",
    amount: 8500,
  },
  {
    order_id: "ORD-041",
    customer_id: "CUST-013",
    item: "照明 リングライト",
    status: "delivered",
    amount: 4200,
  },
  {
    order_id: "ORD-042",
    customer_id: "CUST-047",
    item: "マイク USB",
    status: "shipped",
    amount: 9800,
  },
  {
    order_id: "ORD-043",
    customer_id: "CUST-061",
    item: "ストリーミングデッキ",
    status: "pending",
    amount: 22000,
  },
  {
    order_id: "ORD-044",
    customer_id: "CUST-030",
    item: "グリーンバック",
    status: "delivered",
    amount: 3500,
  },
  {
    order_id: "ORD-045",
    customer_id: "CUST-085",
    item: "ビデオキャプチャーボード",
    status: "shipped",
    amount: 12800,
  },
  {
    order_id: "ORD-046",
    customer_id: "CUST-001",
    item: "ゲームコントローラー",
    status: "delivered",
    amount: 7800,
  },
  {
    order_id: "ORD-047",
    customer_id: "CUST-072",
    item: "VRヘッドセット",
    status: "pending",
    amount: 68000,
  },
  {
    order_id: "ORD-048",
    customer_id: "CUST-054",
    item: "Switch用ドック",
    status: "shipped",
    amount: 8900,
  },
  {
    order_id: "ORD-049",
    customer_id: "CUST-037",
    item: "ゲーミングモニター 144Hz",
    status: "delivered",
    amount: 48000,
  },
  {
    order_id: "ORD-050",
    customer_id: "CUST-097",
    item: "ゲーミングキーボード RGB",
    status: "pending",
    amount: 14500,
  },
  {
    order_id: "ORD-051",
    customer_id: "CUST-009",
    item: "電子書籍リーダー",
    status: "shipped",
    amount: 19800,
  },
  {
    order_id: "ORD-052",
    customer_id: "CUST-042",
    item: "スマートスピーカー",
    status: "delivered",
    amount: 11800,
  },
  {
    order_id: "ORD-053",
    customer_id: "CUST-064",
    item: "ロボット掃除機",
    status: "pending",
    amount: 58000,
  },
  {
    order_id: "ORD-054",
    customer_id: "CUST-020",
    item: "空気清浄機",
    status: "shipped",
    amount: 32000,
  },
  {
    order_id: "ORD-055",
    customer_id: "CUST-078",
    item: "電動歯ブラシ",
    status: "delivered",
    amount: 8900,
  },
  {
    order_id: "ORD-056",
    customer_id: "CUST-006",
    item: "スマート体重計",
    status: "delivered",
    amount: 5800,
  },
  {
    order_id: "ORD-057",
    customer_id: "CUST-091",
    item: "フィットネストラッカー",
    status: "shipped",
    amount: 12000,
  },
  {
    order_id: "ORD-058",
    customer_id: "CUST-025",
    item: "血圧計 スマート連携",
    status: "pending",
    amount: 9800,
  },
  {
    order_id: "ORD-059",
    customer_id: "CUST-050",
    item: "ネックマッサージャー",
    status: "delivered",
    amount: 14800,
  },
  {
    order_id: "ORD-060",
    customer_id: "CUST-015",
    item: "アロマディフューザー",
    status: "shipped",
    amount: 3800,
  },
  {
    order_id: "ORD-061",
    customer_id: "CUST-098",
    item: "コーヒーメーカー",
    status: "delivered",
    amount: 22000,
  },
  {
    order_id: "ORD-062",
    customer_id: "CUST-043",
    item: "電気ケトル スマート",
    status: "pending",
    amount: 8500,
  },
  {
    order_id: "ORD-063",
    customer_id: "CUST-067",
    item: "炊飯器 IH",
    status: "shipped",
    amount: 38000,
  },
  {
    order_id: "ORD-064",
    customer_id: "CUST-010",
    item: "フードプロセッサー",
    status: "delivered",
    amount: 16500,
  },
  {
    order_id: "ORD-065",
    customer_id: "CUST-086",
    item: "電子レンジ",
    status: "pending",
    amount: 42000,
  },
  {
    order_id: "ORD-066",
    customer_id: "CUST-032",
    item: "ハンディ掃除機",
    status: "shipped",
    amount: 9800,
  },
  {
    order_id: "ORD-067",
    customer_id: "CUST-053",
    item: "衣類スチーマー",
    status: "delivered",
    amount: 7500,
  },
  {
    order_id: "ORD-068",
    customer_id: "CUST-018",
    item: "除湿機",
    status: "delivered",
    amount: 28000,
  },
  {
    order_id: "ORD-069",
    customer_id: "CUST-074",
    item: "加湿器 超音波",
    status: "shipped",
    amount: 6800,
  },
  {
    order_id: "ORD-070",
    customer_id: "CUST-093",
    item: "LED シーリングライト",
    status: "pending",
    amount: 12000,
  },
  {
    order_id: "ORD-071",
    customer_id: "CUST-036",
    item: "スマート電球セット",
    status: "delivered",
    amount: 5400,
  },
  {
    order_id: "ORD-072",
    customer_id: "CUST-059",
    item: "防犯カメラ 屋外用",
    status: "shipped",
    amount: 18000,
  },
  {
    order_id: "ORD-073",
    customer_id: "CUST-021",
    item: "スマートドアロック",
    status: "pending",
    amount: 24000,
  },
  {
    order_id: "ORD-074",
    customer_id: "CUST-099",
    item: "テレビ 55インチ 4K",
    status: "delivered",
    amount: 98000,
  },
  {
    order_id: "ORD-075",
    customer_id: "CUST-004",
    item: "サウンドバー",
    status: "shipped",
    amount: 28000,
  },
  {
    order_id: "ORD-076",
    customer_id: "CUST-048",
    item: "ブルーレイプレーヤー",
    status: "pending",
    amount: 22000,
  },
  {
    order_id: "ORD-077",
    customer_id: "CUST-077",
    item: "HDDレコーダー",
    status: "delivered",
    amount: 35000,
  },
  {
    order_id: "ORD-078",
    customer_id: "CUST-012",
    item: "Fire TV Stick",
    status: "shipped",
    amount: 5980,
  },
  {
    order_id: "ORD-079",
    customer_id: "CUST-089",
    item: "Chromecast",
    status: "delivered",
    amount: 4800,
  },
  {
    order_id: "ORD-080",
    customer_id: "CUST-029",
    item: "ゲーム機 本体",
    status: "pending",
    amount: 54980,
  },
  {
    order_id: "ORD-081",
    customer_id: "CUST-056",
    item: "ゲームソフト RPG",
    status: "shipped",
    amount: 7800,
  },
  {
    order_id: "ORD-082",
    customer_id: "CUST-040",
    item: "ゲームソフト アクション",
    status: "delivered",
    amount: 6800,
  },
  {
    order_id: "ORD-083",
    customer_id: "CUST-096",
    item: "ゲームカード メモリ 128GB",
    status: "pending",
    amount: 4500,
  },
  {
    order_id: "ORD-084",
    customer_id: "CUST-069",
    item: "スマートフォン ケース",
    status: "shipped",
    amount: 1800,
  },
  {
    order_id: "ORD-085",
    customer_id: "CUST-024",
    item: "スマートフォン 保護フィルム",
    status: "delivered",
    amount: 980,
  },
  {
    order_id: "ORD-086",
    customer_id: "CUST-083",
    item: "スマートフォン 新品",
    status: "pending",
    amount: 132000,
  },
  {
    order_id: "ORD-087",
    customer_id: "CUST-027",
    item: "モバイルバッテリー 20000mAh",
    status: "shipped",
    amount: 5800,
  },
  {
    order_id: "ORD-088",
    customer_id: "CUST-058",
    item: "充電ケーブル セット",
    status: "delivered",
    amount: 2200,
  },
  {
    order_id: "ORD-089",
    customer_id: "CUST-034",
    item: "スマートバンド",
    status: "shipped",
    amount: 8900,
  },
  {
    order_id: "ORD-090",
    customer_id: "CUST-094",
    item: "TWS イヤホン ノイキャン",
    status: "pending",
    amount: 22000,
  },
  {
    order_id: "ORD-091",
    customer_id: "CUST-045",
    item: "ドローン 入門用",
    status: "delivered",
    amount: 42000,
  },
  {
    order_id: "ORD-092",
    customer_id: "CUST-070",
    item: "ラジコンカー",
    status: "shipped",
    amount: 12800,
  },
  {
    order_id: "ORD-093",
    customer_id: "CUST-052",
    item: "3Dプリンター",
    status: "pending",
    amount: 58000,
  },
  {
    order_id: "ORD-094",
    customer_id: "CUST-087",
    item: "はんだごてセット",
    status: "delivered",
    amount: 3800,
  },
  {
    order_id: "ORD-095",
    customer_id: "CUST-065",
    item: "電子工作キット",
    status: "shipped",
    amount: 5200,
  },
  {
    order_id: "ORD-096",
    customer_id: "CUST-080",
    item: "Raspberry Pi 5",
    status: "pending",
    amount: 8900,
  },
  {
    order_id: "ORD-097",
    customer_id: "CUST-062",
    item: "Arduino スターターキット",
    status: "delivered",
    amount: 4500,
  },
  {
    order_id: "ORD-098",
    customer_id: "CUST-075",
    item: "ブレッドボードセット",
    status: "shipped",
    amount: 1800,
  },
  {
    order_id: "ORD-099",
    customer_id: "CUST-092",
    item: "テスター マルチメーター",
    status: "delivered",
    amount: 3200,
  },
  {
    order_id: "ORD-100",
    customer_id: "CUST-081",
    item: "工具セット",
    status: "pending",
    amount: 6800,
  },
];
